version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: idcr umbilical
      POSTGRES_PASSWORD: idcr_pass
      POSTGRES_DB: idcr_db
    volumes:
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./infrastructure/storage/minio_setup.sh:/minio_setup.sh
  api_gateway:
    build: ./microservices/api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
  classification:
    build: ./microservices/classification
    ports:
      - "8001:8001"
    depends_on:
      - db
      - rabbitmq
  routing_engine:
    build: ./microservices/routing_engine
    ports:
      - "8002:8002"
    depends_on:
      - db
      - rabbitmq
  content_analysis:
    build: ./microservices/content_analysis
    ports:
      - "8003:8003"
    depends_on:
      - db
      - rabbitmq
  workflow_integration:
    build: ./microservices/workflow_integration
    ports:
      - "8004:8004"
    depends_on:
      - db
      - rabbitmq